#!/usr/bin/env python3
"""Extract a chrome-free content document out of a baked legacy artifact.

Legacy slugs were generated by substituting an author's canvas into
``template.html``, which froze a copy of the chrome (CSS, popover markup, and
a ~1,100-line inline script) into every published version. A chrome fix
therefore never reached an already-published page — each baked file had to be
hand-patched, and the two front-ends drifted until legacy pages started
swallowing clicks on native ``<select>`` elements.

This module recovers the author's canvas so the server can serve it through
the universal shell instead, where chrome is loaded fresh from the skill
directory on every request. The transform is deliberately deterministic:

* ``template.html`` brackets its ``{{CANVAS}}`` substitution point with
  ``<!-- CANVAS CONTENT`` / ``<!-- END CANVAS CONTENT`` sentinel comments.
  Those survive baking verbatim, so the canvas is a plain string slice — no
  HTML parsing, no heuristics, and nothing to get subtly wrong.
* ``ANCHOR_REGISTRY`` is re-encoded from its baked JS literal into the
  ``<script type="application/json" id="anchor-registry-data">`` block that
  ``adapter.js`` reads. Older artifacts baked a JS object literal rather than
  JSON (single quotes, bare keys), so the decoder tolerates both.

Anchors are keyed by ``data-anchor-id`` / ``id`` attributes that live inside
the canvas slice, so extraction preserves every existing comment anchor;
``comments.json`` is never read or written here.
"""

from __future__ import annotations

import json
import re

CANVAS_START = "<!-- CANVAS CONTENT"
CANVAS_END = "<!-- END CANVAS CONTENT"

_REGISTRY_DECL = re.compile(r"\bconst\s+ANCHOR_REGISTRY\s*=\s*")

# Baked pages reference chrome assets that only exist next to the artifact.
# The /content route rewrites ../diagram-plot.js itself; anything else the
# author pulled in (CDN tags with SRI, relative data/ fetches) is copied
# through untouched.
_HEAD_ASSET_RE = re.compile(
    r'<script\b[^>]*\bsrc="(?:\.\./)?diagram-plot\.js"[^>]*>\s*</script>', re.I
)


class ExtractionError(ValueError):
    """The document does not carry the sentinels an extraction needs."""


def has_canvas_sentinels(html: str) -> bool:
    """True when `html` is a baked artifact this module can extract."""
    start = html.find(CANVAS_START)
    if start == -1:
        return False
    return html.find(CANVAS_END, start) != -1


def extract_canvas(html: str) -> str:
    """Return the author's canvas markup from a baked artifact."""
    start = html.find(CANVAS_START)
    if start == -1:
        raise ExtractionError("no CANVAS CONTENT sentinel")
    open_end = html.find("-->", start)
    if open_end == -1:
        raise ExtractionError("unterminated CANVAS CONTENT sentinel")
    end = html.find(CANVAS_END, open_end)
    if end == -1:
        raise ExtractionError("no END CANVAS CONTENT sentinel")
    return html[open_end + 3:end].strip()


def _slice_braced(text: str, start: int) -> str:
    """Return the {...} literal beginning at `start`, brace-matched.

    String-aware so a brace inside an anchor label cannot end the slice early.
    """
    depth = 0
    quote = None
    escaped = False
    for i in range(start, len(text)):
        ch = text[i]
        if quote:
            if escaped:
                escaped = False
            elif ch == "\\":
                escaped = True
            elif ch == quote:
                quote = None
            continue
        if ch in "\"'":
            quote = ch
        elif ch == "{":
            depth += 1
        elif ch == "}":
            depth -= 1
            if depth == 0:
                return text[start:i + 1]
    raise ExtractionError("unbalanced ANCHOR_REGISTRY literal")


def _js_object_to_json(src: str) -> str:
    """Normalize a JS object literal into JSON.

    Handles the two pre-JSON shapes found in baked artifacts: bare identifier
    keys (``{name:'x'}``) and single-quoted strings. Runs outside of string
    literals only, so label text is never rewritten.
    """
    out = []
    quote = None
    escaped = False
    i = 0
    while i < len(src):
        ch = src[i]
        if quote:
            if escaped:
                escaped = False
                out.append(ch)
            elif ch == "\\":
                escaped = True
                out.append(ch)
            elif ch == quote:
                quote = None
                out.append('"')
            elif ch == '"' and quote == "'":
                out.append('\\"')
            else:
                out.append(ch)
            i += 1
            continue
        if ch in "\"'":
            quote = ch
            out.append('"')
            i += 1
            continue
        # Bare key -> quoted key, only where a key may legally start.
        m = re.match(r"([A-Za-z_$][\w$]*)\s*:", src[i:])
        if m and (not out or out[-1].strip()[-1:] in "{,"):
            out.append('"%s":' % m.group(1))
            i += m.end()
            continue
        out.append(ch)
        i += 1
    text = "".join(out)
    text = re.sub(r",(\s*[}\]])", r"\1", text)  # trailing commas
    return text


def extract_registry(html: str) -> dict:
    """Return the baked ANCHOR_REGISTRY as a dict ({} when absent)."""
    m = _REGISTRY_DECL.search(html)
    if not m:
        return {}
    brace = html.find("{", m.end())
    if brace == -1:
        return {}
    literal = _slice_braced(html, brace)
    try:
        return json.loads(literal)
    except json.JSONDecodeError:
        pass
    try:
        return json.loads(_js_object_to_json(literal))
    except json.JSONDecodeError as exc:
        raise ExtractionError(f"could not decode ANCHOR_REGISTRY: {exc}") from exc


def _extract_head_assets(html: str) -> str:
    """Carry author/script tags the canvas depends on into the content head.

    Only diagram-plot.js is relocated: the /content route rewrites its path to
    a cache-stamped URL. CDN tags with SRI live inside the canvas slice and
    travel with it untouched.
    """
    head_end = html.find("</head>")
    head = html[:head_end] if head_end != -1 else ""
    tags = _HEAD_ASSET_RE.findall(head)
    if _HEAD_ASSET_RE.search(head):
        return '<script src="../diagram-plot.js"></script>\n'
    return "".join(tags)


def build_content_document(html: str, title: str = "") -> str:
    """Build the chrome-free content document for a baked artifact.

    The result is what ``content/<version>.html`` would have contained had the
    artifact been authored chrome-free: the canvas, the anchor registry in the
    JSON form ``adapter.js`` reads, and nothing else. The server injects
    ``adapter.js`` into it at request time.
    """
    canvas = extract_canvas(html)
    registry = extract_registry(html)
    head_assets = _extract_head_assets(html)

    safe_title = (title or "Annotate content").replace("<", "&lt;").replace(">", "&gt;")
    registry_json = json.dumps(registry, ensure_ascii=False)

    return f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{safe_title}</title>
{head_assets}</head>
<body>
<div id="canvas-wrapper">
{canvas}
</div>
<script type="application/json" id="anchor-registry-data">{registry_json}</script>
</body>
</html>
"""
