"""Write a provider's skill directory from the packaged skill text.

The package is canonical; a skill directory (``~/.claude/skills/annotate``,
a skills-org checkout, ``~/.agents/skills/annotate``) is a deployment of it
and holds no code. ``annotate install-skill --provider claude --dest DIR``
writes into DIR:

    SKILL.md                    the provider's skill text, invocation section
                                rewritten to `annotate <cmd>` with the
                                `python3 -m agent_annotate.cli` fallback
    references/*.md             the one set of references, copied verbatim
    hooks/check-comment-bus.sh  a shim that execs the packaged hook, so a
                                settings.json entry pointing into the skill
                                directory keeps working
    agents/openai.yaml          Codex only

Every write is atomic and happens only when the content differs; nothing in
the destination is ever deleted. The function returns one line per file
saying what happened, so a second run prints "unchanged" for everything.
"""

from __future__ import annotations

import os
import re
import sys
from pathlib import Path

from .paths import HOOK_SCRIPT, PACKAGE_DIR

SKILLS_DIR = PACKAGE_DIR / "skills"
PROVIDERS = ("claude", "codex")

GENERATED_MARK = "generated by `annotate install-skill`"

INVOCATION_BLOCK = (
    "```bash\n"
    "annotate <cmd>                        # the agent-annotate entry point (uv tool install / pip)\n"
    "python3 -m agent_annotate.cli <cmd>   # fallback whenever `command -v annotate` is not this package\n"
    "```"
)

_INVOCATION_RE = re.compile(
    r"(^## 1\. Invocation\s*\n\s*\n)```bash\n.*?\n```",
    re.MULTILINE | re.DOTALL,
)
_FRONTMATTER_RE = re.compile(r"\A---\n.*?\n---\n", re.DOTALL)


def skill_source(provider: str) -> Path:
    if provider not in PROVIDERS:
        raise ValueError(f"unknown provider {provider!r}; expected one of {', '.join(PROVIDERS)}")
    return SKILLS_DIR / provider


def render_skill_md(provider: str, text: str) -> str:
    """The provider's SKILL.md with the invocation block normalised and a
    generated-file marker after the frontmatter."""
    rendered, n = _INVOCATION_RE.subn(lambda m: m.group(1) + INVOCATION_BLOCK, text, count=1)
    if n == 0:
        raise ValueError(f"{provider} SKILL.md has no '## 1. Invocation' code block to rewrite")
    marker = (
        f"<!-- {GENERATED_MARK} --provider {provider}; source: "
        f"agent_annotate/skills/{provider}/SKILL.md in the agent-annotate package. "
        "Edit the package, then regenerate. -->\n"
    )
    fm = _FRONTMATTER_RE.match(rendered)
    if fm:
        return rendered[:fm.end()] + marker + rendered[fm.end():]
    return marker + rendered


def hook_shim(python: str | None = None) -> str:
    """A check-comment-bus.sh that runs the packaged hook of THIS install.

    The packaged script is preferred (it locates its Python next to itself and
    never consults `annotate` on PATH, which may be libgd). The interpreter
    that installed the skill is the fallback; a bare python3 the last resort.
    Always exits 0: a prompt is never blocked.
    """
    py = python or sys.executable
    return (
        "#!/usr/bin/env bash\n"
        f"# check-comment-bus.sh — {GENERATED_MARK}; do not edit.\n"
        "# UserPromptSubmit hook shim: execs the packaged hook of the agent-annotate\n"
        "# install that generated this directory, so the skill directory holds no code.\n"
        "# Always exits 0 — never block a prompt.\n"
        "set -u\n"
        f'PKG_HOOK="{HOOK_SCRIPT}"\n'
        f'PY="{py}"\n'
        '[ -f "$PKG_HOOK" ] && exec bash "$PKG_HOOK" "$@"\n'
        '[ -x "$PY" ] && exec "$PY" -m agent_annotate.hooks.check_comment_bus "$@"\n'
        "for cmd in python3 python; do\n"
        '    if command -v "$cmd" >/dev/null 2>&1; then\n'
        '        exec "$cmd" -m agent_annotate.hooks.check_comment_bus "$@"\n'
        "    fi\n"
        "done\n"
        "exit 0\n"
    )


def planned_files(provider: str, python: str | None = None) -> dict[str, tuple[str, int]]:
    """{relative path: (content, mode)} for everything install_skill writes."""
    src = skill_source(provider)
    files: dict[str, tuple[str, int]] = {}
    files["SKILL.md"] = (render_skill_md(provider, (src / "SKILL.md").read_text(encoding="utf-8")), 0o644)
    # The references are one set, kept with the Claude skill; every provider ships them.
    refs = SKILLS_DIR / "claude" / "references"
    for ref in sorted(refs.glob("*.md")):
        files[f"references/{ref.name}"] = (ref.read_text(encoding="utf-8"), 0o644)
    for extra in sorted((src / "agents").glob("*.yaml")) if (src / "agents").is_dir() else []:
        files[f"agents/{extra.name}"] = (extra.read_text(encoding="utf-8"), 0o644)
    files["hooks/check-comment-bus.sh"] = (hook_shim(python), 0o755)
    return files


def _write_atomic(path: Path, content: str, mode: int) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_name(path.name + ".tmp")
    tmp.write_text(content, encoding="utf-8")
    os.chmod(tmp, mode)
    os.replace(tmp, path)


def install_skill(provider: str, dest: Path, python: str | None = None) -> list[str]:
    """Write the provider skill into `dest`. Returns one report line per file:
    'wrote', 'updated', 'mode' (content same, execute bit fixed) or 'unchanged'."""
    dest = Path(dest).expanduser().resolve()
    lines: list[str] = []
    for rel, (content, mode) in planned_files(provider, python).items():
        target = dest / rel
        if target.is_file():
            try:
                current = target.read_text(encoding="utf-8")
            except UnicodeDecodeError:
                current = None
            if current == content:
                if mode & 0o111 and not os.access(target, os.X_OK):
                    os.chmod(target, mode)
                    lines.append(f"mode       {rel}")
                else:
                    lines.append(f"unchanged  {rel}")
                continue
            _write_atomic(target, content, mode)
            lines.append(f"updated    {rel}")
        else:
            _write_atomic(target, content, mode)
            lines.append(f"wrote      {rel}")
    return lines
